steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Deploy to Cloud Run Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      [
        'functions', 'deploy', 'website-server-reverse-proxy',
        '--gen2',
        '--source', '.',                # deploy source directory
        '--region', 'us-central1',      # your region
        '--runtime', 'nodejs22',        # choose: nodejs18, nodejs20, python, go, etc.
        '--entry-point', 'handler',     # the exported function name
        '--trigger-http',
        '--allow-unathenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

