steps:
# Step 1: Build training component Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/belkaml-trainer:${_COMMIT_SHA}',
    '-t', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/belkaml-trainer:latest',
    '-f', 'src/vertex_ai/components/training/Dockerfile',
    '.'
  ]

# Step 2: Push training component image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/belkaml-trainer']

# Step 3: Install Python dependencies and compile pipeline YAML
- name: 'python:3.12'
  entrypoint: 'bash'
  env: ['PYTHONPATH=/workspace/src']
  args:
    - '-c'
    - |
      pip install google-cloud-aiplatform kfp
      cd src/vertex_ai
      python jobs/train_pipeline_job.py

# Step 4: Upload compiled pipeline YAML to GCS
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['cp', 'src/vertex_ai/train_pipeline.yaml', 'gs://belkaml_pipeline_artifacts/train_pipeline.yaml']

# Step 5 (OPTIONAL): Automatically trigger pipeline run
# Uncomment the step below to enable automatic pipeline execution after deployment
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'gcloud'
#   args: [
#     'ai', 'pipelines', 'run',
#     '--display-name=Train pipeline run - ${_COMMIT_SHA}',
#     '--project=${_PROJECT_ID}',
#     '--region=northamerica-northeast2',
#     '--file=gs://belkaml_pipeline_artifacts/train_pipeline.yaml',
#     '--parameter-values', 'bq_project_id=belkaml,bq_project_location=US,bq_dataset_id=belka_train_dataset,bq_table_id=all_data,aip_project_id=belkaml,aip_project_location=northamerica-northeast2,stratify_column=protein_name,y_column=binds'
#   ]

images:
- 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/belkaml-trainer:${_COMMIT_SHA}'
- 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/belkaml-trainer:latest'

substitutions:
  _PROJECT_ID: 'required'
  _COMMIT_SHA: 'latest'

# options:
#   logging: CLOUD_LOGGING_ONLY
