steps:
# 1. Build the container
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}',
    '--build-arg', 'FUNCTION_TARGET=new_data_ingest_entrypoint',
    '.'
  ]

# 2. Push the container to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}']

# 3. Deploy the new image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'new-data-ingest-entrypoint',
    '--image', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}',
    '--region', 'northamerica-northeast2',
    '--service-account', '${_PROJECT_ID}@appspot.gserviceaccount.com',
    '--no-allow-unauthenticated'
  ]

# 4. Ensure the Eventarc trigger exists
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud eventarc triggers create new-data-ingest-entrypoint \
        --location=northamerica-northeast2 \
        --destination-run-service=new-data-ingest-entrypoint \
        --destination-run-region=northamerica-northeast2 \
        --event-filters="type=google.cloud.storage.object.v1.finalized" \
        --event-filters="bucket=belkaml_new_data" \
        --service-account=${_PROJECT_ID}@appspot.gserviceaccount.com \
        || echo "Trigger creation failed; assuming it already exists and continuing."

images:
- 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}'

substitutions:
  _PROJECT_ID: 'required'
  _COMMIT_SHA: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY