# src/ingestion/cloudbuild.yaml
steps:
# 1. Build the container
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}',
    '--build-arg', 'FUNCTION_TARGET=new_data_ingest_entrypoint',
    '.'  # <-- '.' now correctly refers to the 'src/ingestion' folder
  ]

# 2. Push the container
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}']

# 3. Deploy to Cloud Run
- name: 'gcr.io/google-github-actions/setup-gcloud'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'new-data-ingest-entrypoint',
    '--image', 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}',
    '--region', 'northamerica-northeast2',
    '--service-account', '${_PROJECT_ID}@appspot.gserviceaccount.com',
    '--no-allow-unauthenticated'
  ]

# 4. Ensure Eventarc trigger
- name: 'gcr.io/google-github-actions/setup-gcloud'
  entrypoint: gcloud
  args: [
    'eventarc', 'triggers', 'create', 'new-data-ingest-entrypoint',
    # ... all other trigger args ...
  ]
  id: 'create-trigger'

# 5. Handle "already exists" error
- name: 'gcr.io/google-github-actions/setup-gcloud'
  entrypoint: 'bash'
  args: ['-c', 'echo "Trigger already exists."']
  waitFor: ['-create-trigger'] # Runs on failure of previous step

images:
- 'northamerica-northeast2-docker.pkg.dev/${_PROJECT_ID}/belka-repo/new-data-ingest:${_COMMIT_SHA}'