gcs:
  # The bucket to move files to after they are processed successfully
  archive_bucket_name: "your-processed-data-archive-bucket" 

bigquery:
  project: "your-gcp-project-id"
  dataset: "your_dataset_name"
  table: "your_binding_affinity_table"

data_preprocessing:
  experimental_batch_num: 1
  timezone: "UTC"
  col_name_map:
    molecule_id: "molecule_smiles"
    protein_id: "protein_name"
    bind_value: "binds"

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"