name: Deploy Serving Component

on:
  push:
    branches:
      - main
      - test_deploy
    paths:
      - "src/vertex_ai/components/serving.py"
      - "src/vertex_ai/components/serving/Dockerfile"
      - "src/vertex_ai/pipelines/deploy_pipeline.py"
      - "src/vertex_ai/jobs/deploy_pipeline_job.py"
      - "src/vertex_ai/cloudbuild/serving/cloudbuild.yaml"
      - ".github/workflows/deploy-serving.yml"

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Submit Serving Build
        run: |
          gcloud builds submit . \
            --config=./src/vertex_ai/cloudbuild/serving/cloudbuild.yaml \
            --substitutions="_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},_COMMIT_SHA=${{ github.sha }}" \
            --suppress-logs
